### ISSUE TITLE
Can't get login as root in secure_installation.yml

### ISSUE THREAD

**Issue by beata** [debops/ansible-mariadb_server#39]
I ran into an strange situation today.
This role works fine before, but fails today (2017/01/10).

It fails every time executing `mysql_user` module in `tasks/secure_installation.yml `, an authentication error would be thrown. 
I tried login to mysql with `mysql -uroot` on target machine, then I got an authentication error too.

After search on the web, I found out that "Change root password under safe mode" could avoid this issue.
https://ubuntuforums.org/showthread.php?t=2275033&p=13272315#post13272315

Not sure what causes this problem, I've made a workaround(https://github.com/beata/ansible-mariadb_server/commit/1fe7d107e502647c014136a265edfc66f6763e01) to make the installation work.

Here's my environment:
```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

mariadb_server__flavor: mariadb_upstream
mariadb_server__upstream_version: '10.1'
mariadb_server__bind_address: '::'
```

**Comment by drybjed** [comment]
Do you have the `/root/.my.cnf` file on the remote host? It should contain `root` password and should be used by the `mysql` tool automatically when you try to log in.

The solution you found is a way to reset a forgotten `root` database password, it's not a good solution to initialize a new password.

Does the error happen when you install the version provided with your distribution instead of the upstream version? Perhaps upstream changed something in their packages.

**Comment by mmack** [comment]
I have the exact same problem. I have the my.cnf file, it's with the right password. However the root account has no password at all and therefor a normal "mysql" command as root fails because it tries to login with the my.cnf credentials... strange thing here...

**Comment by mmack** [comment]
This describes to problem:
http://stackoverflow.com/questions/40050219/rootlocalhost-password-set-with-ansible-mysql-user-module-doesnt-work

**Comment by drybjed** [comment]
Thanks, it seems that the issue will show up on MySQL 5.7+, so most likely either in upstream packages or on newer Ubuntu installations. I'll see what I can do about the passwords.

**Comment by mmack** [comment]
This before the installing helps:
```
- name: Specify MySQL root password before installing
  # without this, auth_socket will be used for root@localhost, and we won't be able to set the password
  debconf: name='mariadb-server-10.1' question='mysql-server/root_password' value='{{mariadb_server__root_password | quote}}' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mariadb-server-10.1' question='mysql-server/root_password_again' value='{{mariadb_server__root_password | quote}}' vtype='password'
  become: true```

**Comment by drybjed** [comment]
Putting passwords in the `debconf` database is problematic, since it depends on the specific package name, in this case `mariadb-server-10.1`. This probably would need to be conditional and role would need to check the package version before installing it, which currently is not done with that need in mind.

Right now at least on Debian Stretch it looks like distribution version of MariaDB works as expected, ie. `mysql` command on `root` account can connect to the database. I'll close this issue for now, so that it doesn't block the merge of the DebOps roles into unified `git` repository, and if it shows up again it can be worked on then.
